[theme]
background = "#191414"
primary = "#FFFFFF"
secondary = "light black"
title = "#5b4965"
playing = "#5b4965"
playing_selected = "#5b4965"
playing_bg = "#191414"
highlight = "#FFFFFF"
highlight_bg = "#484848"
error = "#FFFFFF"
error_bg = "red"
statusbar = "#191414"
statusbar_progress = "#5b4965"
statusbar_bg = "#5b4965"
cmdline = "#FFFFFF"
cmdline_bg = "#191414"
search_match = "light red"
